// Supabase Edge Function: horoscope
// One genuine, varied daily Cancer reading per person, generated by Claude and
// cached per day so both phones match and it only generates once. Mirrors the
// day-story pattern (raw Anthropic HTTP, output_config json_schema, service-role
// cache). Verify JWT OFF; reuses the ANTHROPIC_API_KEY secret.

const MODEL = "claude-opus-4-8";
const ANTHROPIC_URL = "https://api.anthropic.com/v1/messages";
const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
const json = (b: unknown, s = 200) =>
  new Response(JSON.stringify(b), { status: s, headers: { ...cors, "content-type": "application/json" } });

const SYSTEM = [
  "You are an astrologer writing a SHORT daily horoscope for a couple — two people, both Cancer ♋.",
  "For each person, in the given order, write a DISTINCT reading for the given date: warm, specific, gently playful, present tense, 1–2 sentences, max ~180 characters. Avoid clichés and generic filler; make the two people's readings feel different from each other, and make each day feel different from the last (let the date inspire the angle).",
  "Then a `closer`: one short fun line — a lucky window, a tiny nudge, or a wink — max ~60 characters.",
  "They're a loving couple; you may gently nod to togetherness, but don't name the other person. No emoji, no quotes, no markdown.",
].join(" ");

const SCHEMA = {
  type: "object",
  properties: {
    readings: {
      type: "array",
      items: { type: "object", properties: { reading: { type: "string" }, closer: { type: "string" } }, required: ["reading", "closer"], additionalProperties: false },
    },
  },
  required: ["readings"],
  additionalProperties: false,
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  try {
    const { day, people = [] } = await req.json();
    if (!day || !people.length) return json({ error: "day + people required" }, 400);
    const sbUrl = Deno.env.get("SUPABASE_URL");
    const svc = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

    // already generated today? return the cached reading (keeps both phones in sync)
    if (sbUrl && svc) {
      try {
        const r = await fetch(`${sbUrl}/rest/v1/horoscope_cache?day=eq.${day}&select=data`, {
          headers: { apikey: svc, Authorization: `Bearer ${svc}` },
        });
        const rows = await r.json();
        if (Array.isArray(rows) && rows[0] && rows[0].data) return json(rows[0].data);
      } catch { /* fall through to generate */ }
    }

    const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
    if (!apiKey) return json({ error: "ANTHROPIC_API_KEY not set" }, 500);
    const roster = people.map((p: any, i: number) =>
      `${i + 1}) ${p.name || "Person " + (i + 1)} — Cancer${p.birthday ? ", b. " + p.birthday : ""}.`).join(" ");
    const prompt = `Date: ${day}. People, in order: ${roster} Write today's readings (one per person, in order).`;

    const resp = await fetch(ANTHROPIC_URL, {
      method: "POST",
      headers: { "x-api-key": apiKey, "anthropic-version": "2023-06-01", "content-type": "application/json" },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 500,
        system: SYSTEM,
        output_config: { format: { type: "json_schema", schema: SCHEMA } },
        messages: [{ role: "user", content: [{ type: "text", text: prompt }] }],
      }),
    });
    if (!resp.ok) return json({ error: "anthropic " + resp.status, detail: await resp.text() }, 502);
    const out = await resp.json();
    const raw = (out.content || []).filter((b: any) => b.type === "text").map((b: any) => b.text).join("").trim();
    let data: any = null;
    try { data = JSON.parse(raw); } catch { return json({ error: "bad model output" }, 502); }
    if (!data || !Array.isArray(data.readings) || !data.readings.length) return json({ error: "empty readings" }, 502);
    data.readings = data.readings.slice(0, people.length).map((r: any) => ({
      reading: String(r.reading || "").slice(0, 220),
      closer: String(r.closer || "").slice(0, 80),
    }));

    // cache for the rest of the day
    if (sbUrl && svc) {
      try {
        await fetch(`${sbUrl}/rest/v1/horoscope_cache?on_conflict=day`, {
          method: "POST",
          headers: { apikey: svc, Authorization: `Bearer ${svc}`, "content-type": "application/json", Prefer: "resolution=merge-duplicates" },
          body: JSON.stringify({ day, data }),
        });
      } catch { /* best effort */ }
    }
    return json(data);
  } catch (e) {
    return json({ error: String((e as Error).message || e) }, 500);
  }
});
